# Generated by Django 3.2.4 on 2022-02-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inheritance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelwithinheritance',
            options={'base_manager_name': 'objects'},
        ),
    ]
